(autoload 'igrep-insinuate                      "igrep" "" t)
(autoload 'igrep                                "igrep" "" t)
(autoload 'igrep-find                           "igrep" "" t)
(autoload 'igrep-visited-files                  "igrep" "" t)
(autoload 'dired-do-igrep                       "igrep" "" t)
(autoload 'dired-do-igrep-find                  "igrep" "" t)
(autoload 'Buffer-menu-igrep                    "igrep" "" t)
(autoload 'igrep-insert-default-regex           "igrep" "" t)
(autoload 'igrep-insert-default-files           "igrep" "" t)
(provide 'igrep-mode-epackage-install)
